from . import InstructionData

_LOGIC_INSNS = (
    InstructionData(name='ADC',    mnem='adc',    sig='000111rdddddrrrr', op_order='dr', flags='zcnvsh'),
    InstructionData(name='ADD',    mnem='add',    sig='000011rdddddrrrr', op_order='dr', flags='zcnvsh'),
    InstructionData(name='ADIW',   mnem='adiw',   sig='10010110KKddKKKK', op_order='dK', flags='zcnvs'),
    InstructionData(name='AND',    mnem='and',    sig='001000rdddddrrrr', op_order='dr', flags='znvs'),
    InstructionData(name='ANDI',   mnem='andi',   sig='0111KKKKddddKKKK', op_order='dK', flags='znvs'),
    InstructionData(name='CLR',    mnem='clr',    sig='001001rdddddrrrr', op_order='dr', flags='znvs'),
    InstructionData(name='COM',    mnem='com',    sig='1001010ddddd0000', op_order='d',  flags='zcnvs'),
    InstructionData(name='DEC',    mnem='dec',    sig='1001010ddddd1010', op_order='d',  flags='znvs'),
    InstructionData(name='DES',    mnem='des',    sig='10010100KKKK1011', op_order='K'),
    InstructionData(name='EOR',    mnem='eor',    sig='001001rdddddrrrr', op_order='dr', flags='znvs'),
    InstructionData(name='FMUL',   mnem='fmul',   sig='000000110ddd1rrr', op_order='dr', flags='zc'),
    InstructionData(name='FMULS',  mnem='fmuls',  sig='000000111ddd0rrr', op_order='dr', flags='zc'),
    InstructionData(name='FMULSU', mnem='fmulsu', sig='000000111ddd1rrr', op_order='dr', flags='zc'),
    InstructionData(name='INC',    mnem='inc',    sig='1001010ddddd0011', op_order='d',  flags='znvs'),
    InstructionData(name='MUL',    mnem='mul',    sig='100111rdddddrrrr', op_order='dr', flags='zc'),
    InstructionData(name='MULS',   mnem='muls',   sig='00000010ddddrrrr', op_order='dr', flags='zc'),
    InstructionData(name='MULSU',  mnem='mulsu',  sig='000000110ddd0rrr', op_order='dr', flags='zc'),
    InstructionData(name='NEG',    mnem='neg',    sig='1001010ddddd0001', op_order='d',  flags='zcnvsh'),
    InstructionData(name='OR',     mnem='or',     sig='001010rdddddrrrr', op_order='dr', flags='znvs'),
    InstructionData(name='ORI',    mnem='ori',    sig='0110KKKKddddKKKK', op_order='dK', flags='znvs'),
    InstructionData(name='SBC',    mnem='sbc',    sig='000010rdddddrrrr', op_order='dr', flags='zcnvsh'),
    InstructionData(name='SBCI',   mnem='sbci',   sig='0100KKKKddddKKKK', op_order='dK', flags='zcnvsh'),
    InstructionData(name='SBIW',   mnem='sbiw',   sig='10010111KKddKKKK', op_order='dK', flags='zcnvs'),
    InstructionData(name='SER',    mnem='ser',    sig='11101111dddd1111', op_order='d'),
    InstructionData(name='SUB',    mnem='sub',    sig='000110rdddddrrrr', op_order='dr', flags='zcnvsh'),
    InstructionData(name='SUBI',   mnem='subi',   sig='0101KKKKddddKKKK', op_order='dK', flags='zcnvsh'),
    InstructionData(name='TST',    mnem='tst',    sig='001000rdddddrrrr', op_order='dr', flags='znvs')
    )
